# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: microsoft/setup-msbuild@v1.1
      with:
        dotnet-version: 4.6.1
    - name: Restore dependencies
      run: nuget restore 
    - name: Build
      run: msbuild build .//ConsoleApp1//ConsoleApp1.csproj
